name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.12.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      PORT: ${{secrets.PORT}}


    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - name: Change Directory
        run: cd /root/invoice/actions-invoice-backend/_work/icchaporon-invoice-express/icchaporon-invoice-express
      - run: pm2 restart ecosystem.config.js
